[workspace]
members = ["download-symbols", "fake-tecken", "tempdir", "upload-symbols"]
resolver = "3"

[workspace.package]
version = "0.3.0"
edition = "2024"
repository = "https://github.com/mozilla-services/upload-symbols"

[workspace.dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive", "env"] }
reqwest = { version = "0.13.3" }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.1" }
tracing = "0.1.44"
url = "2.5.8"
zip = "8.6.0"


[package]
name = "upload-symbols-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
libc = "0.2.186"
opentelemetry = { version = "0.32.0", default-features = false, features = ["metrics", "trace"] }
opentelemetry-otlp = { version = "0.32.0", default-features = false, features = ["trace", "http-proto", "reqwest-blocking-client", "metrics"] }
opentelemetry-semantic-conventions = "0.32.0"
opentelemetry_sdk = { version = "0.32.0", default-features = false, features = ["metrics", "trace"] }
reqwest = { workspace = true }
sentry = { version = "0.48.0", default-features = false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-opentelemetry = { version = "0.33.0", default-features = false, features = ["metrics", "smallvec"] }
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["ansi", "env-filter", "fmt", "smallvec", "std"] }
upload-symbols = { path = "upload-symbols", features = ["clap"] }
url = { workspace = true }

[[bin]]
name = "upload-symbols"
path = "src/main.rs"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
