[package]
name = "upload-symbols"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
clap = { workspace = true, optional = true }
flate2 = "1.1.9"
md-5 = { version = "0.11.0", default-features = false, features = ["alloc"] }
reqwest = { workspace = true, features = ["json", "multipart", "stream"] }
serde = { workspace = true }
tempdir = { path = "../tempdir" }
thiserror = "2.0.18"
tokio = { workspace = true, features = ["rt", "sync", "time"] }
tokio-util = { version = "0.7.18", features = ["io"] }
tracing = { workspace = true }
walkdir = "2.5.0"
zip = { workspace = true }

[dev-dependencies]
fake-tecken = { path = "../fake-tecken" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
clap = ["dep:clap"]
