name: Rust tests and linters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  test:
    name: Run tests and linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - run: cargo clippy --workspace
      - run: cargo test --workspace
      - run: cargo doc --workspace --no-deps
      - run: cargo fmt --all --check
